from cnboonhan/base

RUN pip3 install jupyterlab

CMD [ "jupyter-lab", "--ip", "0.0.0.0", "--port", "8899", "--allow-root" , "--ServerApp.password=''", "--ServerApp.token=''", "--notebook-dir='/root'" ]
